### ISSUE TITLE
Possible to add wakeup command? 

### ISSUE THREAD

**Issue by kjettern** [XattSPT/homey-SomaSmartShades#10]
Hello! Sometimes my shades is not responding after I send the command. It's almost like the device need to wake up before it can receive commands? Will it be possible to add a wakeup command to send, before you send the actual command of opening or closing the shades?

**Comment by XattSPT** [comment]
Dear @kjettern , the problem is not in Soma Shades or the App. This problem is usually is related to Homey Bluettoth manage. They are changing thins in every version and seems they are solving those problems. 

I usually have a flow to reboot homey every night and after rebooting bluetooth at 95% times works correctly. 

Hope this helps!
