### ISSUE TITLE
Smart shades stop responding

### ISSUE THREAD

**Issue by marcobernardini4** [XattSPT/homey-SomaSmartShades#11]
Hi, I'm trying to pair my smart shades.
If I pair 2 of them is working, but if I try to pair them all( 10 in total) it stops working. 
I'm running 5.0.0-rc.34 homey and I installed the app from the homey app store.
Is there any walkthrough to follow?

**Comment by XattSPT** [comment]
dear @marcobernardini4, sorry for late reply. 

10 Shades are a lot of shades!! 

Some things you can try, bluettoth is slow technology and they contact every shade step by step, so you should try to put a waiting time between action to shade (in my morning routine I have a 30seconds waiting between every shade).

If the problem is adding them, you should try to add them on groups of two or three.

Do not hesistate to contact me if I can help ou in any way,

G.
