### ISSUE TITLE
Coexist with Soma Connect

### ISSUE THREAD

**Issue by ghost** [XattSPT/homey-SomaSmartShades#2]
Is there a way to Make the Homey drop it's connection with the smart blind as soon as it finished sending the command? I ask this because i also use a soma connect for Homekit (The homekit apps for Homey does not work right with your app, you cant set % and it's very unstable)

I guess if Homey drops the connection to the smart blinds faster it would not make the blinds unresponsive in the Home app.

It seems that only one device can be connected to s smart blind at the same time.

**Comment by XattSPT** [comment]
Dear @malmentm,

   Homey app drops connection after sending any command. And it reconnects every "x minutes" that can be configured in the app in order to update information of all Blinds. 

   Regarding Homekit App, I've opened an issue to HomeyKit app to update their app to allow any %. Nowadays app only works on 0% / 50% or 100%. It's a very easy change on the app, probably you can branch HomeyKit app easily and install it to your Homey 

(see https://github.com/swttt/com.swttt.homekit/issues/172)

   Regarding Soma Connect I've bricked mine some time ago , so I can't try how it coexists with Homey. I'm using Homey coexisting with Soma APP and also with Node-red and I can interact with soma to all of them.

**Comment by ghost** [comment]
Ok, i understand. I would use only the HomeyKit app if i could but somehow when i use it it also messes up the calibration of my blinds

**Comment by XattSPT** [comment]
@malmentm I've done a brach when I've testing this issue with HomeyKit. 

if you want to install to your homey you can clone it at:

https://github.com/XattSPT/com.swttt.homekit

It allows you better control of shades on Homeykit, but I noticed that not always is updating all state on homekit app. 

I'll will use for a while trying to see if I could help on decalibration...

**Comment by ghost** [comment]
Did you get it working with Homeykit? With % ?

**Comment by XattSPT** [comment]
I’ll publish a new beta in a couple of days with a better integration with Homeykit and also % position. I’m doing last tests with it. At the moment it works fine.

**Comment by ghost** [comment]
Great!
