### ISSUE TITLE
Soma Tilt

### ISSUE THREAD

**Issue by AdyRock** [XattSPT/homey-SomaSmartShades#5]
Do you have any plans to add support for the Soma Tilt modules?

The current app finds them and I can tilt them down but it doesn't seem any of the other controls are working so I can't open the blinds (set to horizontal).

Thanks, Ady.

**Comment by XattSPT** [comment]
@AdyRock, I can try to  support Tilt modules, but I'll need some help because I do not have this kind of module.

If you are interested, I can develop a test app in order to try to get missing parameters, and you can install it and give them to me. 

I'm not sure if it will work, but we can try it if you are interested.

Some questions:
1) As I undestand you can close tilt module but you can not open it?
2) Can you move them with on/off?
3) Can you move them with three buttons screen? (up/idle/down)
4) is battery working?

Thanks in advance,

**Comment by AdyRock** [comment]
I would be very happy to help in any way I can. I am happy to run test versions via the store or install versions via the CLI by grabbing them from Github.

The situation is actually quite good. I had some initial issues which I think is due to Homey being on the edge of the bluetooth range for my blinds which made it look like things don't work.

So this is what works:
1. Up button moves to the fully tilt down position.
2. Down button moves to the fully tilt up position.
3. Idle button stops the movement.
4. Slider works where the control is fully filed (open) moves the blinds to the tilt down position, fully empty (closed) moves the blind to the tilt up position and positions in between move to the expected partial position, e.g. slider in mid position for blinds to be horizontal (open).
5. The on / off button moves the blind to the mid position when turned on (set to 50%) and the tilt up position when off (set to  0%).
6. The battery reporting is also correct.

So everything works except it feels like it's backwards. Maybe there could be an option to reverse the direction so tilt up is 100% instead of 0%?

The only other issue is the different controls don't seem to sync so toggling the switch does not update the slider, etc.

Is it possible to get the current position from the blinds or is it a one-way communication to just set the position?

Thanks for looking into this.

**Comment by XattSPT** [comment]
That sounds really good. Let me do a test version (I’ll try next weekend).
It sounds easier than I expected.

I’ll be uploading a brach on Github if you use CLI. It will be faster for
me.

Regarding sync, today I uploaded a test version witch try to solve that (U
should set time expected for finish operation and refresh on each device
settings to optimize)

https://homey.app/en-us/app/com.somasmarthome/Soma-Smart-Shade/test/


El dg, 17 nov 2019 a les 20:42 AdyRock <notifications@github.com> va
escriure:

**Comment by AdyRock** [comment]
Cool. I have installed the test version and the update time feature is looking good.
Does that update on a regular basis or just a one off after a move command from Homey?
If it's a one shot then a time of 15 seconds would be good for my blinds. If it polls regularly then I can understand it not wanting to be to frequent but a regular polling every 30 seconds would be great to keep homey in sync with external factors.

**Comment by XattSPT** [comment]
@AdyRock, looking on your problem, I think there is an additional step to do before to change program... could you please try to reconfigure your device on SOMA App being carefully when they ask you to fix up position and down position steps?

I think it is possible to set devices backwards if up point and down point are confgured in reverse order, and the app goes correctly but Homey App doesn't. 

Please try it, and tell me if all works correctly. 

Regardind your las question, in app settings you can configure polling refresh time to refresh status at regular basis (between 5 and 15 minutes).
Added step in las revision is for each device and makes a refresh after sending a command. I will change low interval to 15sec in next revision, but you shoud be aware that BLE it is not a fast technology and blocks any other commands to be contacted (for example Soma APP). It should be adjusted on each device according to the time is needed to establish connection (depends on distance of Homey and Device) and moving time. 

I tried to connect as minimum time possible to any device in order to allow other sistems to get updated. To give you an easy example, SOMA APP blocks connection on a device. If you open a device on SOMA APP and try to send commands through Homey, you can not do it. I've tried to minimize connections and time connection to not to interfere in any other system you can use (homekit thought SOMA Connect, home assistant, .....)

**Comment by AdyRock** [comment]
I have written an app that controls my soma motors via the connect module. That uses the HTTP protocol to the hub (RaspberryPi) instead of bluetooth to the motor. This overcomes the problem with Homeys limited bluetooth range not reaching to the blinds location very well.

Do you mind if I ask Athom to publish it or is it something you want to write yourself?

I don't want to step on your toes so I will only published if you are OK with that.

**Comment by XattSPT** [comment]
@AdyRock I have no problem if you want to publish. 

I've bricked my soma-connect years ago, and nowadays leaving my raspberry pi devices trying to put all together direcly to Homey. I used HTTP through RPi during some time.

Feel free to contact me if you need to test your app with soma shades (I have three).

It could be an option also, to add your development in this app as a Device (HTTP) if you are interested. Or if Athom don't want to publish... at your choice.

Let me insist, if you have time and if you don't mind, to try to reconfigure your tilt throught soma app to verify if this app works correctly with soma tilt? It will be very helpful for me. If this doesn't work I should seriously need to think about 'inverse mode' or something like that. 

Thanks in advance,

G.

**Comment by AdyRock** [comment]
I'm not sure if you have seen but Soma have the image for the latest version of their connect hub on their website. So maybe you can resurrect yours using that. The HTTP  protocol requires the latest connect update to work anyway.
If you want to add my code to your app I am fine with that but obviously that's more work for you to combine it.
I still have tweaks to do as I currently have some fixed data that needs to be added to configuration screens but it is basically working well. All my kitchen blinds had opened this morning as expected for the first time. 
I will try to reconnect a blind this evening as per your suggestion.

**Comment by AdyRock** [comment]
I have pushed my app to Athom to see what they say. Meanwhile the code is located on GitHub:
https://github.com/AdyRock/com.soma.connect
If you would like me to include you as a contributor in the app.json then let me know what you would like me to add.
