### ISSUE TITLE
Verification of sent command?

### ISSUE THREAD

**Issue by ghost** [XattSPT/homey-SomaSmartShades#6]
Is it possible to add some verification to know if the smart shade har recieved the command? Because sometimes when i try to close the blind it does not respond it seems but the status chages to "closed" anyway in the app. And maybe add som retries if the blinds do not respond.

**Comment by XattSPT** [comment]
Dear @malmentm i've done some updates to try to fix this bug, there were some cases that open/close state does not update properly. 

You can test new version on https://homey.app/en-us/app/com.somasmarthome/Soma-Smart-Shade/test/

Please note in device settings you should adapt spent time from open to close position in order to check status after a given order. 

please, do not hesitate to contact me if you have any further suggestion or malfunction.

Thanks for your comments.

G.
