### ISSUE TITLE
Not working after last update? 

### ISSUE THREAD

**Issue by kjettern** [XattSPT/homey-SomaSmartShades#7]
After last homey update, the sunscreen does not respond anymore. No battery indication either. Homey is placed at the same spot as before, and the sunscreen does work with the Soma android app.

**Comment by XattSPT** [comment]
If Soma android app also do not respond, seems that problem is that device is not working, not from Homey Soma App. Double check if device is charged or try to reconfigure it.

You should resolve problem with Soma App, and then should work with Homey. This app only connects with bluetooth, if your device is not working, it can not read battery data.

**Comment by kjettern** [comment]
I meant to say that the sunscreen do work with the android app, only not with homey. Battery is 90%

**Comment by XattSPT** [comment]
You are right, mines has stopped working too :( 

I'll take a look, but seems BLE has some errors on new Homey software (other app's are failing too). 

Hope they will solve soon.

**Comment by XattSPT** [comment]
@kjettern mine working fine after last update on Homey. Are yours ok?

**Comment by kjettern** [comment]
> @kjettern mine working fine after last update on Homey. Are yours ok?

Yes it's working again.. Little bit buggy, but what can you expect from Bluetooth.
